services:
  # imlsreact:
  #   image: imlsreact
  #   build:
  #     context: ./fe2
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 4000:4000
  #     - 9229:9229
  #   command: ['node', '--inspect=0.0.0.0:9229', 'index.js']

  fastapiserver:
    image: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 5001
    ports:
      - 5001:5001
    # depends_on:
    #   - imlsreact

  internetnews-server:
    image: cclauss/inn
    ports:
      - 119:119
      - 563:563
